### ISSUE TITLE
Circular call to script handler

### ISSUE THREAD

**Issue by tonybyng** [doublethreedigital/sc-starter-kit#38]
Hi

Just cloned the git repo as suggested and run  composer install

and got (at the end)

>  - Installing doublethreedigital/simple-commerce (dist): Extracting archive
> 130/130 [============================] 100%
>                                                                   
>  [RuntimeException]                                               
>  Circular call to script handler 'post-package-install' detected  
>
>install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-scripts] [--no-progress] [->-no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader->prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] 
>[<packages>]...

Any thoughts ?

**Comment by duncanmcclean** [comment]
Which version of composer are you on? You should be able to check by running `composer -V`.

**Comment by tonybyng** [comment]
Hi
Thanks for the quick response. 2.0.2

**Comment by tonybyng** [comment]
Just ran it through with composer 1.10.19 and no errors.

Many thanks

**Comment by duncanmcclean** [comment]
There was an issue with early versions of Composer 2 with the archive issues. If you update to the latest version of Composer 2, it should resolve the issue.
